name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Testing Julia ${{ matrix.version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: ['1.10', '1.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia/packages
            ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ hashFiles('Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ matrix.version }}-

      - name: Install dependencies
        run: | 
          rm -f Manifest.toml 
          julia --project=. -e ' using Pkg; Pkg.instantiate();'
            
      - name: Run tests
        run: julia --project=. test/CodeCoverage.jl

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "lcov.info"
          fail_ci_if_error: false