name: ControlDashboard CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
permissions:
  actions: write
  contents: read

jobs:
  setup:
    name: Julia ${{ matrix.version }} setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.10', '1.11', '1.12.0-rc3']
    steps:
      - name: Julia Environment Setup
        uses: ./.github/actions/julia-project-setup
        with:
          julia-version: ${{ matrix.version }}
   
  test:
    needs: setup
    name: Julia ${{ matrix.version }} Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.10', '1.11', '1.12.0-rc3']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for changed Julia files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            src/**/*.jl
            test/**/*.jl
      - name: Cache dependencies
        if: ${{ steps.changed-files.outputs.any_changed }} == 'true'
        uses: julia-actions/cache@v1
        with:
          cache-name: julia_${{ matrix.version }}_cache
      - name: Run Tests
        if: ${{ steps.changed-files.outputs.any_changed }} == 'true'
        working-directory: ${{ github.workspace }}
        shell: bash
        run: | 
          echo "Running tests for Julia ${{ matrix.version }} ..."
          julia --project=. -e 'test/CodeCoverage.jl'
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov-${{ matrix.version }}
          path: lcov.info

  upload-codecov:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: lcov-1.11
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "lcov.info"

  documentation:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: julia-actions/cache@v1
        with:
          cache-name: julia_1.11_cache
      - name: Build and deploy documentation
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: Documenter 
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate();'
          julia --project=docs docs/make.jl
