name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Julia ${{ matrix.version }} Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: ['1.10', '1.11', '1.12.0-rc3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      - name: Cache dependencies
        uses: julia-actions/cache@v1

      - name: Install dependencies
        run: | 
          rm -f Manifest.toml 
          julia --project=. -e 'using Pkg; Pkg.instantiate();'
            
      - name: Run tests
        run: julia --project=. test/CodeCoverage.jl

      - name: Upload coverage to Codecov
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: codecov/codecov-action@v5
        with:
          files: "lcov.info"
          fail_ci_if_error: false